[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/data/usuarios_web.json"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-store"
